export const jsonData = [
    {
      "RequestID": 1007599,
      "RequestID_Previous": "",
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Create)",
      "Role": "Requester",
      "BusinessProcess_Prev": "",
      "Scenario_Prev": "",
      "Role_Prev": "",
      "StartedOn": "5/30/2022",
      "FinishedOn": "6/9/2022",
      "FinishedBy": "FColasa",
      "DurationMinutes": 4662,
      "Duration": "8 Days,  5 Hrs, 42 Mins",
      "System": "EU2",
      "State": "Completed"
    },
    {
      "RequestID": 1007599,
      "RequestID_Previous": "",
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Create)",
      "Role": "JBS",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Create)",
      "Role_Prev": "Requester",
      "StartedOn": "6/9/2022",
      "FinishedOn": "6/10/2022",
      "FinishedBy": "DPIEDFOR",
      "DurationMinutes": 440,
      "Duration": "0 Days,  7 Hrs, 20 Mins",
      "System": "EU2",
      "State": "Completed"
    },
    {
      "RequestID": 1007599,
      "RequestID_Previous": "",
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Create)",
      "Role": "Post",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Create)",
      "Role_Prev": "JBS",
      "StartedOn": "6/10/2022",
      "FinishedOn": "6/10/2022",
      "FinishedBy": "process",
      "DurationMinutes": 1,
      "Duration": "0 Days,  0 Hrs,  1 Min",
      "System": "EU2",
      "State": "Completed"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "JBS",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Create)",
      "Role_Prev": "Post",
      "StartedOn": "6/10/2022",
      "FinishedOn": "6/10/2022",
      "FinishedBy": "DPIEDFOR",
      "DurationMinutes": 1,
      "Duration": "0 Days,  0 Hrs,  1 Min",
      "System": "EU2",
      "State": "Completed"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "Deliver EDN",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Create)",
      "Role_Prev": "Post",
      "StartedOn": "6/10/2022",
      "FinishedOn": "6/13/2022",
      "FinishedBy": "pkilaru",
      "DurationMinutes": 162,
      "Duration": "0 Days,  2 Hrs, 42 Mins",
      "System": "EU2",
      "State": "Completed"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "Data Ops",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Create)",
      "Role_Prev": "Post",
      "StartedOn": "6/10/2022",
      "FinishedOn": "6/13/2022",
      "FinishedBy": "AB3",
      "DurationMinutes": 418,
      "Duration": "0 Days,  6 Hrs, 58 Mins",
      "System": "EU2",
      "State": "Completed"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "BOM",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Create)",
      "Role_Prev": "Post",
      "StartedOn": "6/10/2022",
      "FinishedOn": "8/1/2022",
      "FinishedBy": "process",
      "DurationMinutes": 19028,
      "Duration": "35 Days,  2 Hrs,  8 Mins",
      "System": "EU2",
      "State": "Completed"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "Deliver Trans",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "JBS",
      "StartedOn": "6/13/2022",
      "FinishedOn": "6/17/2022",
      "FinishedBy": "JSCHELL",
      "DurationMinutes": 2540,
      "Duration": "4 Days,  6 Hrs, 20 Mins",
      "System": "EU2",
      "State": "InProgress"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "Deliver Trans",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "Deliver EDN",
      "StartedOn": "6/13/2022",
      "FinishedOn": "6/17/2022",
      "FinishedBy": "JSCHELL",
      "DurationMinutes": 2540,
      "Duration": "4 Days,  6 Hrs, 20 Mins",
      "System": "EU2",
      "State": "InProgress"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "Planner",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "JBS",
      "StartedOn": "6/13/2022",
      "FinishedOn": "8/1/2022",
      "FinishedBy": "GRaja2",
      "DurationMinutes": 18866,
      "Duration": "34 Days,  8 Hrs, 26 Mins",
      "System": "EU2",
      "State": "InProgress"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "Planner",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "Deliver EDN",
      "StartedOn": "6/13/2022",
      "FinishedOn": "8/1/2022",
      "FinishedBy": "GRaja2",
      "DurationMinutes": 18866,
      "Duration": "34 Days,  8 Hrs, 26 Mins",
      "System": "EU2",
      "State": "InProgress"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "MD Reviewer",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "Deliver Trans",
      "StartedOn": "8/1/2022",
      "FinishedOn": "8/1/2022",
      "FinishedBy": "ELUCANTO",
      "DurationMinutes": 189,
      "Duration": "0 Days,  3 Hrs,  9 Mins",
      "System": "EU2",
      "State": "Upcoming"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "MD Reviewer",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "Planner",
      "StartedOn": "8/1/2022",
      "FinishedOn": "8/1/2022",
      "FinishedBy": "ELUCANTO",
      "DurationMinutes": 189,
      "Duration": "0 Days,  3 Hrs,  9 Mins",
      "System": "EU2",
      "State": "Upcoming"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "MD Reviewer",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "Data Ops",
      "StartedOn": "8/1/2022",
      "FinishedOn": "8/1/2022",
      "FinishedBy": "ELUCANTO",
      "DurationMinutes": 189,
      "Duration": "0 Days,  3 Hrs,  9 Mins",
      "System": "EU2",
      "State": "Upcoming"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "MD Reviewer",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "BOM",
      "StartedOn": "8/1/2022",
      "FinishedOn": "8/1/2022",
      "FinishedBy": "ELUCANTO",
      "DurationMinutes": 189,
      "Duration": "0 Days,  3 Hrs,  9 Mins",
      "System": "EU2",
      "State": "Upcoming"
    },
    {
      "RequestID": 1008230,
      "RequestID_Previous": 1007599,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan)",
      "Role": "Post",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "MD Reviewer",
      "StartedOn": "8/1/2022",
      "FinishedOn": "8/1/2022",
      "FinishedBy": "process",
      "DurationMinutes": 1,
      "Duration": "0 Days,  0 Hrs,  1 Min",
      "System": "EU2",
      "State": "Upcoming"
    },
    {
      "RequestID": 1010624,
      "RequestID_Previous": 1008230,
      "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
      "Scenario": "Finished Good (Made) - New (Plan External)",
      "Role": "JBS",
      "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
      "Scenario_Prev": "Finished Good (Made) - New (Plan)",
      "Role_Prev": "Post",
      "StartedOn": "8/1/2022",
      "FinishedOn": "8/2/2022",
      "FinishedBy": "ADVOCHT",
      "DurationMinutes": 590,
      "Duration": "1 Day,   0 Hrs, 50 Mins",
      "System": "EU2",
      "State": "Upcoming"
    }
  ];